### ISSUE TITLE
Get self.poses_2d_mean, self.poses_2d_std with downloading h36m_dataset

### ISSUE THREAD

**Issue by vishnusanjayrs** [Shimingyi/MotioNet#34]
Can you please provide the normalization values for self.poses_2d_mean, self.poses_2d_std  so that i can run the a Test on wild videos .

(motionet) C:\Users\v84153490\PycharmProjects\MotioNet-master>python evaluate.py -r ./checkpoints/wild_gt_tcc.pth -i sample_output
Building the network
Traceback (most recent call last):
  File "evaluate.py", line 145, in <module>
    main(config, args, output_folder)
  File "evaluate.py", line 73, in main
    parameters = [torch.from_numpy(np.array(item)).float().to(device) for item in h36m_loader(config, is_training=True).dataset.get_parameters()]
  File "C:\Users\v84153490\PycharmProjects\MotioNet-master\data\data_loaders.py", line 11, in __init__
    self.dataset = h36m_dataset.h36m_dataset(config, is_train=is_training)
  File "C:\Users\v84153490\PycharmProjects\MotioNet-master\data\h36m_dataset.py", line 22, in __init__
    positions_set = np.load('./data/data_h36m.npz', allow_pickle=True)['positions_3d'].item()
  File "C:\Anaconda\envs\motionet\lib\site-packages\numpy\lib\npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './data/data_h36m.npz'

**Comment by Shimingyi** [comment]
Hi @vishnusanjayrs , you can download it with this [link](https://drive.google.com/drive/folders/1mvRPqtsNp46grBQ9feYish8evhEkm_9O?usp=sharing).

**Comment by vishnusanjayrs** [comment]
Thanks
